development:
  address: "smtp.gmail.com"
  port: "465"
  user_name: "bumpintoarun"
  password: "vintage1908"
  authentication: "plain" # plain, login, or cram_md5
  domain: "localhost:3000"
  outgoing_address: " "

# or to use sendmail --
#
# development:
#   delivery_method: "sendmail"

test:
  delivery_method: "test"

production:
  address: "smtp.example.com"
  port: "25"
  user_name: "user"
  password: "password"
  authentication: "plain" # plain, login, or cram_md5
  domain: "example.com"
  outgoing_address: "canvas@example.com"

